server:
  port: 8080
  staticPath: "./static"

database:
  schema: "dbschema"
  user: "dbuser"
  password: "dbpassword"

mail:
  host: "localhost"
  port: 25

jwt:
  secret: "${JWT_SECRET}"
  expiryHours: 72

oauth2:
  sidan:
    clientId: "666"
    clientSecret: "s1d4n"
    redirectURL: "auth/sidan/authorized"
    scopes: ["user:email"]
  google:
    clientId: "1234"
    clientSecret: "secret"
    redirectURL: "google/dummy"
    scopes: ["openid", "email"]
  github:
    clientId: "54321"
    clientSecret: "really_secret"
    redirectURL: "github/dummy"
    scopes: ["user:email"]
